### ISSUE TITLE
[Feature Request] For P25 trunking systems, have one VFO for CC and another for VC

### ISSUE THREAD

**Issue by invader-zimm** [cropinghigh/sdrpp-vhfvoiceradio#1]
Hi,
I don't know if it's possible with the open source version of DSD, but it would be nice to be able to tune one VFO to a P25 (or other trunking system) control channel, and have another VFO (or more) jump to voice channels, as directed by the CC VFO. Something like how sdrtrunk does it.

**Comment by cropinghigh** [comment]
unfortunately, currently i know not enough to make this. trying to move everything to the new DSD and still not understand what are the purpose of each P25 packet type. DSD just throws away tons of data, in which, i guess, voice channels info is encoded too.

**Comment by invader-zimm** [comment]
Ah I see. No worries, maybe it will be possible at some point in the future. Thanks for your work, this plugin is awesome
