### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by amitpathania** [cropinghigh/sdrpp-vhfvoiceradio#4]
Not able to compile the code. Error in 'make' command

src/dsp/dsd.h:2:10: fatal error: dsp/processor.h: No such file or directory
 #include <dsp/processor.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/vhfvoiceradio.dir/build.make:75: recipe for target 'CMakeFiles/vhfvoiceradio.dir/src/dsp/dsd_demod.cpp.o' failed
make[2]: *** [CMakeFiles/vhfvoiceradio.dir/src/dsp/dsd_demod.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/vhfvoiceradio.dir/all' failed
make[1]: *** [CMakeFiles/vhfvoiceradio.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cropinghigh** [comment]
I guess you have outdated version of SDR++ headers. Try updating them

**Comment by amitpathania** [comment]
I did fresh compilation of latest version of sdrpp code from github

**Comment by amitpathania** [comment]
Any other suggestions to resolve the issue?Not able to resolve the error

**Comment by amitpathania** [comment]
Issue resolved. Forgot to copy core headers
cd "SDRPlusPlus/core/src"
sudo mkdir -p "/usr/include/sdrpp_core"
sudo find . -regex ".*\.\(h\|hpp\)" -exec cp --parents \{\} "/usr/include/sdrpp_core" \;
