### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by alphapats** [cropinghigh/sdrpp-vhfvoiceradio#5]
While running make command, I am getting following error:
`
sdrpp-vhfvoiceradio/src/demodulators/wfm.h:52:24: error: cannot convert ‘dsp::stream<dsp::complex_t>*’ to ‘dsp::stream<float>*’
   52 |             recov.init(&demod.rdsOut, 5000.0 / 2375, omegaGain, muGain, 0.01);
      |                        ^~~~~~~~~~~~~
      |                        |
      |                        dsp::stream<dsp::complex_t>*
`

OS: Ubuntu22.0.4

**Comment by alphapats** [comment]
yes.. downloaded the latest SDRplusplus github code and rebuild sdrpp.
I am facing same issue again for this module only. Other modules of yours like tetrademod are working fine.

**Comment by cropinghigh** [comment]
I guess you're using outdated version of sdrpp headers. Update them too. 
I just updated both sdrpp and sdrpp-headers to latest git version and everything compiles normally:
![изображение](https://github.com/cropinghigh/sdrpp-vhfvoiceradio/assets/38228168/d4c37d32-6725-4351-b338-31228ef7d2ab)

**Comment by alphapats** [comment]
I have again updated both sdrpp and sdrpp-headers but still getting the same error while compiling.

**Comment by cropinghigh** [comment]
Oh, i'm sorry, i've checked tetra-demod for some reason

**Comment by cropinghigh** [comment]
Fixed by [ee1b3f6](https://github.com/cropinghigh/sdrpp-vhfvoiceradio/commit/ee1b3f63510fe415f2a2847be19b8326838709f9)

**Comment by alphapats** [comment]
Now working after your update
